In [2]:
import requests
from bs4 import BeautifulSoup
import scipy.io
import matplotlib.pyplot as plt
import matplotlib 
import pandas as pd
import numpy as np
import pickle
from time import sleep
import timeit

In [3]:
def request(msg, slp=1):
    status_code = 500  # Want to get a status-code of 200
    while status_code != 200:
        sleep(slp)  # Don't ping the server too often
        try:
            r = requests.get(msg)
            status_code = r.status_code
            if status_code != 200:
                print("Server Error! Response Code %i. Retrying..." % (r.status_code))
        except:
            print("An exception has occurred, probably a momentory loss of connection. Waiting one seconds...")
            sleep(1)
    return r

In [4]:
# Initialize a DF to hold all our scraped game info
df_all = pd.DataFrame(columns=["id", "name", "nrate", "pic_url"])
min_nrate = 1e5
npage = 1

# Scraping successful pages in the results until we get down to games with < 1000 ratings each
while min_nrate > 1000:
    # Get full HTML for a specific page in the full listing of boardgames sorted by nrates 
    r = request("https://boardgamegeek.com/browse/boardgame/page/%i?sort=numvoters&sortdir=desc" % (npage,))
    soup = BeautifulSoup(r.text, "html.parser")    
    
    # Get rows for the table listing all the games on this page
    table = soup.find_all("tr", attrs={"id": "row_"})  # Get list of games on this page
    df = pd.DataFrame(columns=["id", "name", "nrate", "pic_url"], index=range(len(table)))  # DF to hold this pages results
    
    # Loop through each row and pull out the info for that game
    for idx, row in enumerate(table):
        # Row may or may not start with a "boardgame rank" link, if YES then strip it
        links = row.find_all("a")
        if "name" in links[0].attrs.keys():
            del links[0]
        gamelink = links[1]  # Get the relative URL for the specific game
        gameid = int(gamelink["href"].split("/")[2])  # Get the game ID by parsing the relative URL
        gamename = gamelink.contents[0]  # Get the actual name of the game as the link contents
        imlink = links[0]  # Get the URL for the game thumbnail
        thumbnail = imlink.contents[0]["src"]

        ratings_str = row.find_all("td", attrs={"class": "collection_bggrating"})[2].contents[0]
        nratings = int("".join(ratings_str.split()))

        df.iloc[idx, :] = [gameid, gamename, nratings, thumbnail]

    # Concatenate the results of this page to the master dataframe
    min_nrate = df["nrate"].min()  # The smallest number of ratings of any game on the page
    print("Page %i scraped, minimum number of ratings was %i" % (npage, min_nrate))
    df_all = pd.concat([df_all, df], axis=0)
    npage += 1
    sleep(2) # Keep the BGG server happy.

Page 1 scraped, minimum number of ratings was 21869
Page 2 scraped, minimum number of ratings was 14115
Page 3 scraped, minimum number of ratings was 10474
Page 4 scraped, minimum number of ratings was 7914
Page 5 scraped, minimum number of ratings was 6720
Page 6 scraped, minimum number of ratings was 5523
Page 7 scraped, minimum number of ratings was 4758
Page 8 scraped, minimum number of ratings was 4175
Page 9 scraped, minimum number of ratings was 3680
Page 10 scraped, minimum number of ratings was 3293
Page 11 scraped, minimum number of ratings was 3000
Page 12 scraped, minimum number of ratings was 2744
Page 13 scraped, minimum number of ratings was 2524
Page 14 scraped, minimum number of ratings was 2356
Page 15 scraped, minimum number of ratings was 2164
Page 16 scraped, minimum number of ratings was 2007
Page 17 scraped, minimum number of ratings was 1863
Page 18 scraped, minimum number of ratings was 1769
Page 19 scraped, minimum number of ratings was 1660
Page 20 scraped, minimum number of ratings was 1577
Page 21 scraped, minimum number of ratings was 1494
Page 22 scraped, minimum number of ratings was 1418
Page 23 scraped, minimum number of ratings was 1357
Page 24 scraped, minimum number of ratings was 1281
Page 25 scraped, minimum number of ratings was 1218
Page 26 scraped, minimum number of ratings was 1153
Page 27 scraped, minimum number of ratings was 1103
Page 28 scraped, minimum number of ratings was 1057
Page 29 scraped, minimum number of ratings was 1012
Page 30 scraped, minimum number of ratings was 976

In [5]:
df = df_all.copy()
# Reset the index
df.reset_index(inplace=True, drop=True)
# Write the DF to .csv for future use
df.to_csv("games_list.csv", index=False, encoding="utf-8")
df.head()

,id,name,nrate,pic_url
0,30549,Pandemic,96289,https://cf.geekdo-images.com/micro/img/0m3-oqB...
1,822,Carcassonne,96272,https://cf.geekdo-images.com/micro/img/z0tTaij...
2,13,Catan,96253,https://cf.geekdo-images.com/micro/img/e0y6Bog...
3,68448,7 Wonders,79916,https://cf.geekdo-images.com/micro/img/h-Ejv31...
4,36218,Dominion,74982,https://cf.geekdo-images.com/micro/img/VYp2s2f...

In [6]:
print("Number of games with > 1000 ratings is approximately %i" % (len(df),))
print("Total number of ratings from all these games is %i" % (df["nrate"].sum(),))

Number of games with > 1000 ratings is approximately 3000
Total number of ratings from all these games is 14006192

In [7]:
min(df["nrate"])

976

In [8]:
len(df)

3000

In [9]:
df.iloc[2999, : ]

id                                                    156089
name                         Arcadia Quest: Beyond the Grave
nrate                                                    976
pic_url    https://cf.geekdo-images.com/micro/img/t-bgPBl...
Name: 2999, dtype: object

In [10]:
df_small_test = df.iloc[2995: , : ].copy()
df_small_test

,id,name,nrate,pic_url
2995,241533,Mansions of Madness: Second Edition – Sanctum ...,978,https://cf.geekdo-images.com/micro/img/C4_W4C-...
2996,37235,Agricola Z-Deck,977,https://cf.geekdo-images.com/micro/img/yrYSRQN...
2997,8552,I Go!,976,https://cf.geekdo-images.com/micro/img/08Sp6on...
2998,20542,Advanced Squad Leader: Starter Kit #3,976,https://cf.geekdo-images.com/micro/img/1Z7Phwo...
2999,156089,Arcadia Quest: Beyond the Grave,976,https://cf.geekdo-images.com/micro/img/t-bgPBl...

In [11]:
df_small_test["nfull_pages"] = (df_small_test["nrate"]-50).apply(round, ndigits=-2)/100
df_small_test

,id,name,nrate,pic_url,nfull_pages
2995,241533,Mansions of Madness: Second Edition – Sanctum ...,978,https://cf.geekdo-images.com/micro/img/C4_W4C-...,9.0
2996,37235,Agricola Z-Deck,977,https://cf.geekdo-images.com/micro/img/yrYSRQN...,9.0
2997,8552,I Go!,976,https://cf.geekdo-images.com/micro/img/08Sp6on...,9.0
2998,20542,Advanced Squad Leader: Starter Kit #3,976,https://cf.geekdo-images.com/micro/img/1Z7Phwo...,9.0
2999,156089,Arcadia Quest: Beyond the Grave,976,https://cf.geekdo-images.com/micro/img/t-bgPBl...,9.0

In [12]:
# testing the API pull
df_ratings_test = pd.DataFrame(columns=["gameid", "username", "rating", "value"], index=range(100))


r = request("http://www.boardgamegeek.com/xmlapi2/thing?id=156089&ratingcomments=1&page=1")
soup = BeautifulSoup(r.text, "xml")
comments = soup("comment")
l1 = [0]*100
l2 = [0]*100
l3 = [0]*100
j = 0
for comm in comments:
    l1[j] = comm["username"]
    l2[j] = float(comm["rating"])
    l3[j] = str(comm["value"])
    j += 1
df_ratings_test.iloc[0:100, df_ratings_test.columns.get_loc("username")] = l1
df_ratings_test.iloc[0:100, df_ratings_test.columns.get_loc("rating")] = l2
df_ratings_test.iloc[0:100, df_ratings_test.columns.get_loc("value")] = l3

In [13]:
df_ratings_test

,gameid,username,rating,value
0,NaN,kryzen13,10,"As a huge fan of the base game, this gets a 10..."
1,NaN,thonnie,10,kickstarter
2,NaN,Dj Silent Bob,10,
3,NaN,SirCptnAwesome,10,
4,NaN,Boltana,10,
...,...,...,...,...
95,NaN,pipkorng,10,
96,NaN,jarchibald,10,
97,NaN,Snivek,10,
98,NaN,yaguiu,10,
99,NaN,SmoovySmoov,10,

In [14]:
df_ratings_test.iloc[0, 3]

'As a huge fan of the base game, this gets a 10 because, as an expansion, it gives me exactly what I want-- even more Arcadia Quest!  A whole new campaign, new heroes (though not my favorites, Chaz is always fun to have and Darryn plays so nice with a couple of the other guys), and the villains and enemies are phenomenal. The Dread King has a killer sculpt, and I love the overkill only enemies.'

In [15]:
df_single_game = df.iloc[2999: , :].copy()
df_single_game

,id,name,nrate,pic_url
2999,156089,Arcadia Quest: Beyond the Grave,976,https://cf.geekdo-images.com/micro/img/t-bgPBl...

In [16]:
df_single_game["nfullpage"] = (df_single_game["nrate"]-50).apply(round, ndigits=-2)/100
df_single_game

,id,name,nrate,pic_url,nfullpage
2999,156089,Arcadia Quest: Beyond the Grave,976,https://cf.geekdo-images.com/micro/img/t-bgPBl...,9.0

In [17]:
df_ratings_single_game = pd.DataFrame(columns=["gameid", "username", "rating", "value"], index=range(1000))

dfidx_start = 0
dfidx = 0

pagenum = 1
fullpages = 9
while fullpages > 0:
    dfidx_end = dfidx_start+100
    df_ratings_single_game.iloc[dfidx_start:dfidx_end, df_ratings_single_game.columns.get_loc("gameid")] = [156089]*100
    sleep(2)
    r = request("http://www.boardgamegeek.com/xmlapi2/thing?id=156089&ratingcomments=1&page=%i" % (pagenum))
    soup = BeautifulSoup(r.text, "xml")
    comments = soup("comment")
    l1 = [0]*100
    l2 = [0]*100
    l3 = [0]*100
    j = 0
    for comm in comments:
        l1[j] = comm["username"]
        l2[j] = float(comm["rating"])
        l3[j] = str(comm["value"])
        j += 1
    df_ratings_single_game.iloc[dfidx_start:dfidx_end, df_ratings_single_game.columns.get_loc("username")] = l1
    df_ratings_single_game.iloc[dfidx_start:dfidx_end, df_ratings_single_game.columns.get_loc("rating")] = l2
    df_ratings_single_game.iloc[dfidx_start:dfidx_end, df_ratings_single_game.columns.get_loc("value")] = l3
    fullpages -= 1
    dfidx_start = dfidx_end     
    pagenum += 1  
    print("pagenum updated to %i" %(pagenum,))
    
df_ratings_single_game = df_ratings_single_game.dropna(how="all")

pagenum updated to 2
pagenum updated to 3
pagenum updated to 4
pagenum updated to 5
pagenum updated to 6
pagenum updated to 7
pagenum updated to 8
pagenum updated to 9
pagenum updated to 10

In [18]:
df_ratings_single_game

,gameid,username,rating,value
0,156089,kryzen13,10,"As a huge fan of the base game, this gets a 10..."
1,156089,thonnie,10,kickstarter
2,156089,Dj Silent Bob,10,
3,156089,SirCptnAwesome,10,
4,156089,Boltana,10,
...,...,...,...,...
895,156089,DDAPROD,7,
896,156089,stanyer,7,
897,156089,hervalix1,7,
898,156089,Keitaro87,7,
899,156089,tanosungae,7,

In [44]:
import MySQLdb
from pandas.io import sql
from sqlalchemy import create_engine

engine = create_engine('mysql+mysqldb://root:LolaHippo74@127.0.0.1:3306/single_test?charset=utf8mb4')
# have to create a connection in MySQL Workbench
# create a database to connect to

In [33]:
df_ratings_single_game.to_sql(name="single_test", con=engine, if_exists="append", index=False)

In [39]:
df_st_group_test = df_small_test.groupby(np.arange(len(df_small_test))//3)

In [40]:
list(df_st_group_test)

[(0,
            id                                               name nrate  \
  2995  241533  Mansions of Madness: Second Edition – Sanctum ...   978
  2996   37235                                    Agricola Z-Deck   977
  2997    8552                                              I Go!   976

                                                  pic_url  nfull_pages
  2995  https://cf.geekdo-images.com/micro/img/C4_W4C-...          9.0
  2996  https://cf.geekdo-images.com/micro/img/yrYSRQN...          9.0
  2997  https://cf.geekdo-images.com/micro/img/08Sp6on...          9.0  ),
 (1,
            id                                   name nrate  \
  2998   20542  Advanced Squad Leader: Starter Kit #3   976
  2999  156089        Arcadia Quest: Beyond the Grave   976

                                                  pic_url  nfull_pages
  2998  https://cf.geekdo-images.com/micro/img/1Z7Phwo...          9.0
  2999  https://cf.geekdo-images.com/micro/img/t-bgPBl...          9.0  )]

In [45]:
for nm, grp in df_small_test.groupby(np.arange(len(df_small_test))//3):
    # Initialize a DF to hold all the responses for this chunk of games
    df_ratings_larger_test = pd.DataFrame(columns=["gameid", "username", "rating", "value"], index=range(grp["nrate"].sum()+100000))

    # Initialize indices for writing to the ratings dataframe
    dfidx_start = 0
    dfidx = 0
    
    # For this group of games, make calls until all FULL pages of every game have been pulled
    pagenum = 1
    while len(grp[grp["nfull_pages"] > 0]) > 0: 
        # Get a restricted DF with only still-active games (have ratings pages left)
        active_games = grp[grp["nfull_pages"] > 0]

        # Set the next chunk of the DF "gameid" column using the list of game IDs
        id_list = []
        for game in active_games["id"]:
            id_list += [game]*100
        dfidx_end = dfidx_start + len(active_games)*100
        df_ratings_larger_test.iloc[dfidx_start:dfidx_end, df_ratings_larger_test.columns.get_loc("gameid")] = id_list

        # Make the request with the list of all game IDs that have ratings left
        id_strs = [str(gid) for gid in active_games["id"]]
        gameids = ",".join(id_strs)
        sleep(1.5)  # Keep the server happy
        r = request("http://www.boardgamegeek.com/xmlapi2/thing?id=%s&ratingcomments=1&page=%i" % (gameids, pagenum))
#         while r.status_code != 200:
#             sleep(2)  # Keep the server happy
#             print("Server Error! Response Code %i. Retrying..." % (r.status_code))
#             r = requests.get("http://www.boardgamegeek.com/xmlapi2/thing?id=%s&ratingcomments=1&page=%i" % (gameids, pagenum))        
        soup = BeautifulSoup(r.text, "xml")
        comments = soup("comment")
#         print("Response status was %i - number of ratings retrieved was %i" % (r.status_code, len(comments)))

        # Parse the response and assign it into the dataframe
        l1 = [0]*len(active_games)*100
        l2 = [0]*len(active_games)*100
        l3 = [0]*len(active_games)*100
        j = 0
        for comm in comments:
            l1[j] = comm["username"]
            l2[j] = float(comm["rating"])
            l3[j] = str(comm["value"])
            j += 1
        df_ratings_larger_test.iloc[dfidx_start:dfidx_end, df_ratings_larger_test.columns.get_loc("username")] = l1
        df_ratings_larger_test.iloc[dfidx_start:dfidx_end, df_ratings_larger_test.columns.get_loc("rating")] = l2
        df_ratings_larger_test.iloc[dfidx_start:dfidx_end, df_ratings_larger_test.columns.get_loc("value")] = l3

        
        grp["nfull_pages"] -= 1  # Decrement the number of FULL pages of each game id
        dfidx_start = dfidx_end     
        pagenum += 1  
        print("pagenum updated to %i" %(pagenum,))
    
    # Strip off the empty rows
    df_ratings_larger_test = df_ratings_larger_test.dropna(how="all")
    # Write this batch of all FULL pages of ratings for this chunk of games to the DB
    df_ratings_larger_test.to_sql(name="larger_test", con=engine, if_exists="append", index=False)    
    print("Processed ratings for batch #%i of games." % (nm))

C:\Users\timco\anaconda3\lib\site-packages\ipykernel_launcher.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

pagenum updated to 2
pagenum updated to 3
pagenum updated to 4
pagenum updated to 5
pagenum updated to 6
pagenum updated to 7
pagenum updated to 8
pagenum updated to 9
pagenum updated to 10
Processed ratings for batch #0 of games.
pagenum updated to 2
pagenum updated to 3
pagenum updated to 4
pagenum updated to 5
pagenum updated to 6
pagenum updated to 7
pagenum updated to 8
pagenum updated to 9
pagenum updated to 10
Processed ratings for batch #1 of games.

In [48]:
# Restore the correct number of FULL pages
df_small_test["nfull_pages"] = (df_small_test["nrate"]-50).apply(round, ndigits=-2)/100  # Round DOWN to nearest 100, then divide by 100

# Initialize a DF to hold all the responses over all the chunks of games
df_ratings_larger_test = pd.DataFrame(columns=["gameid", "username", "rating", "value"], index=range(len(df_small_test)*100))

# Initialize indices for writing to the ratings dataframe
dfidx_start = 0
dfidx = 0

# Loop through game-by-game and request the final page of ratings for each game
for idx, row in df_small_test.iterrows():
    # Get the game ID and the last page number to request
    pagenum = row["nfull_pages"] + 1
    gameid = row["id"]
    
    # Make the request for just the last page of ratings of this game
    sleep(2)  # Keep the server happy
    r = requests.get("http://www.boardgamegeek.com/xmlapi2/thing?id=%i&ratingcomments=1&page=%i" % (gameid, pagenum))
    # while r.status_code != 200:
        # sleep(2)  # Keep the server happy
        # print("Server Error! Response Code %i. Retrying..." % (r.status_code))
        # r = requests.get("http://www.boardgamegeek.com/xmlapi2/thing?id=%i&ratingcomments=1&page=%i" % (gameid, pagenum))
    soup = BeautifulSoup(r.text, "xml")
    comments = soup("comment")
#         print("Response status was %i - length of comments is %i" % (r.status_code, len(comments)))

    # Set the next chunk of the DF "gameids" column with this gameid
    id_list = [gameid]*len(comments)
    dfidx_end = dfidx_start + len(comments)
    df_ratings_larger_test.iloc[dfidx_start:dfidx_end, df_ratings_larger_test.columns.get_loc("gameid")] = id_list

    # Parse the response and assign it into the dataframe
    l1 = [0]*len(comments)
    l2 = [0]*len(comments)
    l3 = [0]*len(comments)
    j = 0
    for comm in comments:
        l1[j] = comm["username"]
        l2[j] = float(comm["rating"])
        l3[j] = str(comm["value"])
        j += 1
    df_ratings_larger_test.iloc[dfidx_start:dfidx_end, df_ratings_larger_test.columns.get_loc("username")] = l1
    df_ratings_larger_test.iloc[dfidx_start:dfidx_end, df_ratings_larger_test.columns.get_loc("rating")] = l2
    df_ratings_larger_test.iloc[dfidx_start:dfidx_end, df_ratings_larger_test.columns.get_loc("value")] = l3

    dfidx_start = dfidx_end   # Increment the starting index for next round        

    if idx%100 == 0:
        print("Finished with a chunk of 3 games.")
        
# Strip off the empty rows
df_ratings_larger_test = df_ratings_larger_test.dropna(how="all")

# Write this final batch of all partial pages of ratings for this chunk of games to the DB
df_ratings_larger_test.to_sql(name="larger_test", con=engine, if_exists="append", index=False)

In [49]:
engine2 = create_engine('mysql+mysqldb://root:LolaHippo74@127.0.0.1:3306/board_games?charset=utf8mb4')

In [50]:
df_games = df.copy()

In [51]:
df_games.head()

,id,name,nrate,pic_url
0,30549,Pandemic,96289,https://cf.geekdo-images.com/micro/img/0m3-oqB...
1,822,Carcassonne,96272,https://cf.geekdo-images.com/micro/img/z0tTaij...
2,13,Catan,96253,https://cf.geekdo-images.com/micro/img/e0y6Bog...
3,68448,7 Wonders,79916,https://cf.geekdo-images.com/micro/img/h-Ejv31...
4,36218,Dominion,74982,https://cf.geekdo-images.com/micro/img/VYp2s2f...

In [52]:
df_games.to_sql(name="games", con=engine2, if_exists="append", index=False)

In [53]:
df_games["nfullpages"] = (df_games["nrate"]-50).apply(round, ndigits=-2)/100

In [54]:
df_games.head()

,id,name,nrate,pic_url,nfullpages
0,30549,Pandemic,96289,https://cf.geekdo-images.com/micro/img/0m3-oqB...,962.0
1,822,Carcassonne,96272,https://cf.geekdo-images.com/micro/img/z0tTaij...,962.0
2,13,Catan,96253,https://cf.geekdo-images.com/micro/img/e0y6Bog...,962.0
3,68448,7 Wonders,79916,https://cf.geekdo-images.com/micro/img/h-Ejv31...,799.0
4,36218,Dominion,74982,https://cf.geekdo-images.com/micro/img/VYp2s2f...,749.0

In [ ]:
for nm, grp in df_games.groupby(np.arange(len(df_games))//150):
    # Initialize a DF to hold all the responses for this chunk of games
    df_ratings = pd.DataFrame(columns=["gameid", "username", "rating", "value"], index=range(grp["nrate"].sum()+100000))

    # Initialize indices for writing to the ratings dataframe
    dfidx_start = 0
    dfidx = 0
    
    # For this group of games, make calls until all FULL pages of every game have been pulled
    pagenum = 1
    while len(grp[grp["nfullpages"] > 0]) > 0: 
        # Get a restricted DF with only still-active games (have ratings pages left)
        active_games = grp[grp["nfullpages"] > 0]

        # Set the next chunk of the DF "gameid" column using the list of game IDs
        id_list = []
        for game in active_games["id"]:
            id_list += [game]*100
        dfidx_end = dfidx_start + len(active_games)*100
        df_ratings.iloc[dfidx_start:dfidx_end, df_ratings.columns.get_loc("gameid")] = id_list

        # Make the request with the list of all game IDs that have ratings left
        id_strs = [str(gid) for gid in active_games["id"]]
        gameids = ",".join(id_strs)
        sleep(2)  # Keep the server happy
        r = request("http://www.boardgamegeek.com/xmlapi2/thing?id=%s&ratingcomments=1&page=%i" % (gameids, pagenum))
#         while r.status_code != 200:
#             sleep(2)  # Keep the server happy
#             print("Server Error! Response Code %i. Retrying..." % (r.status_code))
#             r = requests.get("http://www.boardgamegeek.com/xmlapi2/thing?id=%s&ratingcomments=1&page=%i" % (gameids, pagenum))        
        soup = BeautifulSoup(r.text, "xml")
        comments = soup("comment")
#         print("Response status was %i - number of ratings retrieved was %i" % (r.status_code, len(comments)))

        # Parse the response and assign it into the dataframe
        l1 = [0]*len(active_games)*100
        l2 = [0]*len(active_games)*100
        l3 = [0]*len(active_games)*100
        j = 0
        for comm in comments:
            l1[j] = comm["username"]
            l2[j] = float(comm["rating"])
            l3[j] = str(comm["value"])
            j += 1
        df_ratings.iloc[dfidx_start:dfidx_end, df_ratings.columns.get_loc("username")] = l1
        df_ratings.iloc[dfidx_start:dfidx_end, df_ratings.columns.get_loc("rating")] = l2
        df_ratings.iloc[dfidx_start:dfidx_end, df_ratings.columns.get_loc("value")] = l3

        
        grp["nfullpages"] -= 1  # Decrement the number of FULL pages of each game id
        dfidx_start = dfidx_end     
        pagenum += 1  
        print("pagenum updated to %i" %(pagenum,))
    
    # Strip off the empty rows
    df_ratings = df_ratings.dropna(how="all")
    # Write this batch of all FULL pages of ratings for this chunk of games to the DB
    df_ratings.to_sql(name="ratings", con=engine2, if_exists="append", index=False)    
    print("Processed ratings for batch #%i of games." % (nm))

C:\Users\timco\anaconda3\lib\site-packages\ipykernel_launcher.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

pagenum updated to 2
Server Error! Response Code 502. Retrying...
pagenum updated to 3
Server Error! Response Code 502. Retrying...
pagenum updated to 4
An exception has occurred, probably a momentory loss of connection. Waiting one seconds...
pagenum updated to 5
An exception has occurred, probably a momentory loss of connection. Waiting one seconds...
pagenum updated to 6
Server Error! Response Code 502. Retrying...
pagenum updated to 7
Server Error! Response Code 502. Retrying...
pagenum updated to 8
Server Error! Response Code 502. Retrying...
pagenum updated to 9
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 10
Server Error! Response Code 502. Retrying...
pagenum updated to 11
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 12
Server Error! Response Code 502. Retrying...
pagenum updated to 13
Server Error! Response Code 502. Retrying...
pagenum updated to 14
Server Error! Response Code 502. Retrying...
pagenum updated to 15
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 16
Server Error! Response Code 502. Retrying...
pagenum updated to 17
Server Error! Response Code 502. Retrying...
pagenum updated to 18
Server Error! Response Code 502. Retrying...
pagenum updated to 19
Server Error! Response Code 502. Retrying...
pagenum updated to 20
Server Error! Response Code 502. Retrying...
pagenum updated to 21
Server Error! Response Code 502. Retrying...
pagenum updated to 22
Server Error! Response Code 502. Retrying...
pagenum updated to 23
Server Error! Response Code 502. Retrying...
pagenum updated to 24
pagenum updated to 25
Server Error! Response Code 502. Retrying...
pagenum updated to 26
Server Error! Response Code 502. Retrying...
pagenum updated to 27
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 28
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 29
Server Error! Response Code 502. Retrying...
pagenum updated to 30
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 31
Server Error! Response Code 502. Retrying...
pagenum updated to 32
Server Error! Response Code 502. Retrying...
pagenum updated to 33
Server Error! Response Code 502. Retrying...
pagenum updated to 34
Server Error! Response Code 502. Retrying...
pagenum updated to 35
Server Error! Response Code 502. Retrying...
pagenum updated to 36
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 37
Server Error! Response Code 502. Retrying...
pagenum updated to 38
Server Error! Response Code 502. Retrying...
pagenum updated to 39
Server Error! Response Code 502. Retrying...
pagenum updated to 40
Server Error! Response Code 502. Retrying...
pagenum updated to 41
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 42
Server Error! Response Code 502. Retrying...
pagenum updated to 43
Server Error! Response Code 502. Retrying...
pagenum updated to 44
Server Error! Response Code 502. Retrying...
pagenum updated to 45
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 46
Server Error! Response Code 502. Retrying...
pagenum updated to 47
Server Error! Response Code 502. Retrying...
pagenum updated to 48
Server Error! Response Code 502. Retrying...
pagenum updated to 49
Server Error! Response Code 502. Retrying...
pagenum updated to 50
Server Error! Response Code 502. Retrying...
pagenum updated to 51
Server Error! Response Code 502. Retrying...
pagenum updated to 52
Server Error! Response Code 502. Retrying...
pagenum updated to 53
Server Error! Response Code 502. Retrying...
pagenum updated to 54
Server Error! Response Code 502. Retrying...
pagenum updated to 55
Server Error! Response Code 502. Retrying...
pagenum updated to 56
Server Error! Response Code 502. Retrying...
pagenum updated to 57
Server Error! Response Code 502. Retrying...
pagenum updated to 58
Server Error! Response Code 502. Retrying...
pagenum updated to 59
Server Error! Response Code 502. Retrying...
pagenum updated to 60
Server Error! Response Code 502. Retrying...
pagenum updated to 61
Server Error! Response Code 502. Retrying...
pagenum updated to 62
Server Error! Response Code 502. Retrying...
pagenum updated to 63
Server Error! Response Code 502. Retrying...
pagenum updated to 64
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 65
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 66
Server Error! Response Code 502. Retrying...
pagenum updated to 67
Server Error! Response Code 502. Retrying...
pagenum updated to 68
Server Error! Response Code 502. Retrying...
pagenum updated to 69
Server Error! Response Code 502. Retrying...
pagenum updated to 70
Server Error! Response Code 502. Retrying...
pagenum updated to 71
Server Error! Response Code 502. Retrying...
pagenum updated to 72
Server Error! Response Code 502. Retrying...
pagenum updated to 73
Server Error! Response Code 502. Retrying...
pagenum updated to 74
Server Error! Response Code 502. Retrying...
pagenum updated to 75
Server Error! Response Code 502. Retrying...
pagenum updated to 76
Server Error! Response Code 502. Retrying...
pagenum updated to 77
Server Error! Response Code 502. Retrying...
pagenum updated to 78
Server Error! Response Code 502. Retrying...
pagenum updated to 79
Server Error! Response Code 502. Retrying...
pagenum updated to 80
Server Error! Response Code 502. Retrying...
pagenum updated to 81
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 82
Server Error! Response Code 502. Retrying...
pagenum updated to 83
Server Error! Response Code 502. Retrying...
pagenum updated to 84
Server Error! Response Code 502. Retrying...
pagenum updated to 85
Server Error! Response Code 502. Retrying...
pagenum updated to 86
Server Error! Response Code 502. Retrying...
pagenum updated to 87
Server Error! Response Code 502. Retrying...
pagenum updated to 88
Server Error! Response Code 502. Retrying...
pagenum updated to 89
Server Error! Response Code 502. Retrying...
pagenum updated to 90
Server Error! Response Code 502. Retrying...
pagenum updated to 91
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 92
Server Error! Response Code 502. Retrying...
pagenum updated to 93
Server Error! Response Code 502. Retrying...
pagenum updated to 94
Server Error! Response Code 502. Retrying...
pagenum updated to 95
Server Error! Response Code 502. Retrying...
pagenum updated to 96
Server Error! Response Code 502. Retrying...
pagenum updated to 97
Server Error! Response Code 502. Retrying...
pagenum updated to 98
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 99
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 100
Server Error! Response Code 502. Retrying...
pagenum updated to 101
Server Error! Response Code 502. Retrying...
pagenum updated to 102
Server Error! Response Code 502. Retrying...

pagenum updated to 103
Server Error! Response Code 502. Retrying...
pagenum updated to 104
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 105
Server Error! Response Code 502. Retrying...
pagenum updated to 106
Server Error! Response Code 502. Retrying...
pagenum updated to 107
Server Error! Response Code 502. Retrying...
pagenum updated to 108
Server Error! Response Code 502. Retrying...
pagenum updated to 109
Server Error! Response Code 502. Retrying...
pagenum updated to 110
Server Error! Response Code 502. Retrying...
pagenum updated to 111
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 112
Server Error! Response Code 502. Retrying...
pagenum updated to 113
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 114
Server Error! Response Code 502. Retrying...
pagenum updated to 115
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 116
Server Error! Response Code 502. Retrying...
pagenum updated to 117
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 118
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 119
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 120
Server Error! Response Code 502. Retrying...
pagenum updated to 121
Server Error! Response Code 502. Retrying...
pagenum updated to 122
Server Error! Response Code 502. Retrying...
pagenum updated to 123
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 124
Server Error! Response Code 502. Retrying...
pagenum updated to 125
Server Error! Response Code 502. Retrying...
pagenum updated to 126
Server Error! Response Code 502. Retrying...
pagenum updated to 127
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 128
Server Error! Response Code 502. Retrying...
pagenum updated to 129
Server Error! Response Code 502. Retrying...
pagenum updated to 130
Server Error! Response Code 502. Retrying...
pagenum updated to 131
Server Error! Response Code 502. Retrying...
pagenum updated to 132
Server Error! Response Code 502. Retrying...
pagenum updated to 133
Server Error! Response Code 502. Retrying...
pagenum updated to 134
Server Error! Response Code 502. Retrying...
pagenum updated to 135
Server Error! Response Code 502. Retrying...
pagenum updated to 136
Server Error! Response Code 502. Retrying...
pagenum updated to 137
Server Error! Response Code 502. Retrying...
pagenum updated to 138
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 139
Server Error! Response Code 502. Retrying...
pagenum updated to 140
Server Error! Response Code 502. Retrying...
pagenum updated to 141
Server Error! Response Code 502. Retrying...
pagenum updated to 142
Server Error! Response Code 502. Retrying...
pagenum updated to 143
Server Error! Response Code 502. Retrying...
pagenum updated to 144
Server Error! Response Code 502. Retrying...
pagenum updated to 145
Server Error! Response Code 502. Retrying...
pagenum updated to 146
Server Error! Response Code 502. Retrying...
pagenum updated to 147
Server Error! Response Code 502. Retrying...
pagenum updated to 148
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 149
Server Error! Response Code 502. Retrying...
pagenum updated to 150
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 151
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 152
Server Error! Response Code 502. Retrying...
pagenum updated to 153
Server Error! Response Code 502. Retrying...
pagenum updated to 154
Server Error! Response Code 502. Retrying...
pagenum updated to 155
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 156
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 157
Server Error! Response Code 502. Retrying...
pagenum updated to 158
Server Error! Response Code 502. Retrying...
pagenum updated to 159
Server Error! Response Code 502. Retrying...
pagenum updated to 160
Server Error! Response Code 502. Retrying...
pagenum updated to 161
Server Error! Response Code 502. Retrying...
pagenum updated to 162
Server Error! Response Code 502. Retrying...
pagenum updated to 163
Server Error! Response Code 502. Retrying...
pagenum updated to 164
Server Error! Response Code 502. Retrying...
pagenum updated to 165
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 166
Server Error! Response Code 502. Retrying...
pagenum updated to 167
Server Error! Response Code 502. Retrying...
pagenum updated to 168
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 169
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 170
Server Error! Response Code 503. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 171
Server Error! Response Code 502. Retrying...
pagenum updated to 172
Server Error! Response Code 502. Retrying...
pagenum updated to 173
Server Error! Response Code 502. Retrying...
pagenum updated to 174
Server Error! Response Code 502. Retrying...
pagenum updated to 175
Server Error! Response Code 502. Retrying...
pagenum updated to 176
Server Error! Response Code 502. Retrying...
pagenum updated to 177
Server Error! Response Code 502. Retrying...
Server Error! Response Code 503. Retrying...
pagenum updated to 178
pagenum updated to 179
pagenum updated to 180
pagenum updated to 181
pagenum updated to 182
pagenum updated to 183
pagenum updated to 184
pagenum updated to 185
pagenum updated to 186
pagenum updated to 187
pagenum updated to 188
pagenum updated to 189
pagenum updated to 190
pagenum updated to 191
Server Error! Response Code 502. Retrying...
pagenum updated to 192
pagenum updated to 193
pagenum updated to 194
pagenum updated to 195
pagenum updated to 196
pagenum updated to 197
pagenum updated to 198
pagenum updated to 199
pagenum updated to 200
pagenum updated to 201
pagenum updated to 202
pagenum updated to 203
pagenum updated to 204
pagenum updated to 205
pagenum updated to 206
pagenum updated to 207
pagenum updated to 208
pagenum updated to 209
pagenum updated to 210
pagenum updated to 211
pagenum updated to 212
pagenum updated to 213
pagenum updated to 214
pagenum updated to 215
pagenum updated to 216
pagenum updated to 217
pagenum updated to 218
pagenum updated to 219
pagenum updated to 220

pagenum updated to 221
pagenum updated to 222
pagenum updated to 223
pagenum updated to 224
pagenum updated to 225
pagenum updated to 226
pagenum updated to 227
pagenum updated to 228
pagenum updated to 229
pagenum updated to 230
pagenum updated to 231
pagenum updated to 232
pagenum updated to 233
pagenum updated to 234
pagenum updated to 235
pagenum updated to 236
pagenum updated to 237
pagenum updated to 238
pagenum updated to 239
pagenum updated to 240
pagenum updated to 241
pagenum updated to 242
pagenum updated to 243
pagenum updated to 244
pagenum updated to 245
pagenum updated to 246
pagenum updated to 247
pagenum updated to 248
pagenum updated to 249
pagenum updated to 250
pagenum updated to 251
pagenum updated to 252
pagenum updated to 253
pagenum updated to 254
pagenum updated to 255
pagenum updated to 256
pagenum updated to 257
pagenum updated to 258
pagenum updated to 259
pagenum updated to 260
pagenum updated to 261
pagenum updated to 262
pagenum updated to 263
pagenum updated to 264
pagenum updated to 265
pagenum updated to 266
pagenum updated to 267
pagenum updated to 268
pagenum updated to 269
pagenum updated to 270
pagenum updated to 271
pagenum updated to 272
pagenum updated to 273
pagenum updated to 274
pagenum updated to 275
pagenum updated to 276
pagenum updated to 277
pagenum updated to 278
pagenum updated to 279
pagenum updated to 280
pagenum updated to 281
pagenum updated to 282
pagenum updated to 283
pagenum updated to 284
pagenum updated to 285
pagenum updated to 286
pagenum updated to 287
pagenum updated to 288
pagenum updated to 289
pagenum updated to 290
pagenum updated to 291
pagenum updated to 292
pagenum updated to 293
pagenum updated to 294
pagenum updated to 295
pagenum updated to 296
pagenum updated to 297
pagenum updated to 298
pagenum updated to 299
pagenum updated to 300
pagenum updated to 301
pagenum updated to 302
pagenum updated to 303
pagenum updated to 304
pagenum updated to 305
pagenum updated to 306
pagenum updated to 307
pagenum updated to 308
pagenum updated to 309
pagenum updated to 310
pagenum updated to 311
pagenum updated to 312
pagenum updated to 313
pagenum updated to 314
pagenum updated to 315
pagenum updated to 316
pagenum updated to 317
pagenum updated to 318
pagenum updated to 319
pagenum updated to 320
pagenum updated to 321
pagenum updated to 322
pagenum updated to 323
pagenum updated to 324
pagenum updated to 325
pagenum updated to 326
pagenum updated to 327
pagenum updated to 328
pagenum updated to 329
pagenum updated to 330
pagenum updated to 331
pagenum updated to 332
pagenum updated to 333
pagenum updated to 334
pagenum updated to 335
pagenum updated to 336
pagenum updated to 337
pagenum updated to 338
pagenum updated to 339
pagenum updated to 340
pagenum updated to 341
pagenum updated to 342
pagenum updated to 343
pagenum updated to 344
pagenum updated to 345
pagenum updated to 346
pagenum updated to 347
pagenum updated to 348
pagenum updated to 349
pagenum updated to 350
pagenum updated to 351
pagenum updated to 352
pagenum updated to 353
pagenum updated to 354
pagenum updated to 355
pagenum updated to 356
pagenum updated to 357
pagenum updated to 358
pagenum updated to 359
pagenum updated to 360
pagenum updated to 361
pagenum updated to 362
pagenum updated to 363
pagenum updated to 364
pagenum updated to 365
pagenum updated to 366
pagenum updated to 367
pagenum updated to 368
pagenum updated to 369
pagenum updated to 370
pagenum updated to 371
pagenum updated to 372
pagenum updated to 373
pagenum updated to 374
pagenum updated to 375
pagenum updated to 376
pagenum updated to 377
pagenum updated to 378
pagenum updated to 379
pagenum updated to 380
pagenum updated to 381
pagenum updated to 382
pagenum updated to 383
pagenum updated to 384
pagenum updated to 385
pagenum updated to 386
pagenum updated to 387
pagenum updated to 388
pagenum updated to 389
pagenum updated to 390
pagenum updated to 391
pagenum updated to 392
pagenum updated to 393
pagenum updated to 394
pagenum updated to 395
pagenum updated to 396
pagenum updated to 397
pagenum updated to 398
pagenum updated to 399
pagenum updated to 400
pagenum updated to 401
pagenum updated to 402
pagenum updated to 403
pagenum updated to 404
pagenum updated to 405
pagenum updated to 406
pagenum updated to 407
pagenum updated to 408
pagenum updated to 409
pagenum updated to 410
pagenum updated to 411
pagenum updated to 412
pagenum updated to 413
pagenum updated to 414
pagenum updated to 415
pagenum updated to 416
pagenum updated to 417
pagenum updated to 418
pagenum updated to 419
pagenum updated to 420
pagenum updated to 421
pagenum updated to 422
pagenum updated to 423
pagenum updated to 424
pagenum updated to 425
pagenum updated to 426
pagenum updated to 427
pagenum updated to 428
pagenum updated to 429
pagenum updated to 430
pagenum updated to 431
pagenum updated to 432
pagenum updated to 433
pagenum updated to 434
pagenum updated to 435
pagenum updated to 436
pagenum updated to 437
pagenum updated to 438
pagenum updated to 439
pagenum updated to 440
pagenum updated to 441
pagenum updated to 442
pagenum updated to 443
pagenum updated to 444
pagenum updated to 445
pagenum updated to 446
pagenum updated to 447
pagenum updated to 448
pagenum updated to 449
pagenum updated to 450
pagenum updated to 451
pagenum updated to 452
pagenum updated to 453
pagenum updated to 454
pagenum updated to 455
pagenum updated to 456
pagenum updated to 457
pagenum updated to 458
pagenum updated to 459
pagenum updated to 460
pagenum updated to 461
pagenum updated to 462
pagenum updated to 463
pagenum updated to 464
pagenum updated to 465
pagenum updated to 466
pagenum updated to 467
pagenum updated to 468
pagenum updated to 469
pagenum updated to 470
pagenum updated to 471
pagenum updated to 472
pagenum updated to 473
pagenum updated to 474
pagenum updated to 475
pagenum updated to 476
pagenum updated to 477
pagenum updated to 478
pagenum updated to 479
pagenum updated to 480
pagenum updated to 481
pagenum updated to 482
pagenum updated to 483
pagenum updated to 484
pagenum updated to 485
pagenum updated to 486
pagenum updated to 487
pagenum updated to 488
pagenum updated to 489
pagenum updated to 490
pagenum updated to 491
pagenum updated to 492
pagenum updated to 493
pagenum updated to 494
pagenum updated to 495
pagenum updated to 496
pagenum updated to 497
pagenum updated to 498
pagenum updated to 499
pagenum updated to 500
pagenum updated to 501
pagenum updated to 502
pagenum updated to 503
pagenum updated to 504
pagenum updated to 505
pagenum updated to 506
pagenum updated to 507
pagenum updated to 508
pagenum updated to 509
pagenum updated to 510
pagenum updated to 511
pagenum updated to 512
pagenum updated to 513
pagenum updated to 514
pagenum updated to 515
pagenum updated to 516
pagenum updated to 517
pagenum updated to 518
pagenum updated to 519
pagenum updated to 520
pagenum updated to 521
pagenum updated to 522
pagenum updated to 523
pagenum updated to 524
pagenum updated to 525
pagenum updated to 526
pagenum updated to 527
pagenum updated to 528
pagenum updated to 529
pagenum updated to 530
pagenum updated to 531
pagenum updated to 532
pagenum updated to 533
pagenum updated to 534
pagenum updated to 535
pagenum updated to 536
pagenum updated to 537
pagenum updated to 538
pagenum updated to 539
pagenum updated to 540
pagenum updated to 541
pagenum updated to 542
pagenum updated to 543
pagenum updated to 544
pagenum updated to 545
pagenum updated to 546
pagenum updated to 547
pagenum updated to 548
pagenum updated to 549
pagenum updated to 550
pagenum updated to 551
pagenum updated to 552
pagenum updated to 553
pagenum updated to 554
pagenum updated to 555
pagenum updated to 556
pagenum updated to 557
pagenum updated to 558
pagenum updated to 559
pagenum updated to 560
pagenum updated to 561
pagenum updated to 562
pagenum updated to 563
pagenum updated to 564
pagenum updated to 565
pagenum updated to 566
pagenum updated to 567
pagenum updated to 568
pagenum updated to 569
pagenum updated to 570
pagenum updated to 571
pagenum updated to 572
pagenum updated to 573
pagenum updated to 574
pagenum updated to 575
pagenum updated to 576
pagenum updated to 577

pagenum updated to 578
pagenum updated to 579
pagenum updated to 580
pagenum updated to 581
pagenum updated to 582
pagenum updated to 583
pagenum updated to 584
pagenum updated to 585
pagenum updated to 586
pagenum updated to 587
pagenum updated to 588
pagenum updated to 589
pagenum updated to 590
pagenum updated to 591
pagenum updated to 592
pagenum updated to 593
pagenum updated to 594
pagenum updated to 595
pagenum updated to 596
pagenum updated to 597
pagenum updated to 598
pagenum updated to 599
pagenum updated to 600
pagenum updated to 601
pagenum updated to 602
pagenum updated to 603
pagenum updated to 604
pagenum updated to 605
pagenum updated to 606
pagenum updated to 607
pagenum updated to 608
pagenum updated to 609
pagenum updated to 610
pagenum updated to 611
pagenum updated to 612
pagenum updated to 613
pagenum updated to 614
pagenum updated to 615
pagenum updated to 616
pagenum updated to 617
pagenum updated to 618
pagenum updated to 619
pagenum updated to 620
pagenum updated to 621
pagenum updated to 622
pagenum updated to 623
pagenum updated to 624
pagenum updated to 625
pagenum updated to 626
pagenum updated to 627
pagenum updated to 628
pagenum updated to 629
pagenum updated to 630
pagenum updated to 631
pagenum updated to 632
pagenum updated to 633
pagenum updated to 634
pagenum updated to 635
pagenum updated to 636
pagenum updated to 637
pagenum updated to 638
pagenum updated to 639
pagenum updated to 640
pagenum updated to 641
pagenum updated to 642
pagenum updated to 643
pagenum updated to 644
pagenum updated to 645
pagenum updated to 646
pagenum updated to 647
pagenum updated to 648
pagenum updated to 649
pagenum updated to 650
pagenum updated to 651
pagenum updated to 652
pagenum updated to 653
pagenum updated to 654
pagenum updated to 655
pagenum updated to 656
pagenum updated to 657
pagenum updated to 658
pagenum updated to 659
pagenum updated to 660
pagenum updated to 661
pagenum updated to 662
pagenum updated to 663
pagenum updated to 664
pagenum updated to 665
pagenum updated to 666
pagenum updated to 667
pagenum updated to 668
pagenum updated to 669
pagenum updated to 670
pagenum updated to 671
pagenum updated to 672
pagenum updated to 673
pagenum updated to 674
pagenum updated to 675
pagenum updated to 676
pagenum updated to 677
pagenum updated to 678
pagenum updated to 679
pagenum updated to 680
pagenum updated to 681
pagenum updated to 682
pagenum updated to 683
pagenum updated to 684
pagenum updated to 685
pagenum updated to 686
pagenum updated to 687
pagenum updated to 688
pagenum updated to 689
pagenum updated to 690
pagenum updated to 691
pagenum updated to 692
pagenum updated to 693
pagenum updated to 694
pagenum updated to 695
pagenum updated to 696
pagenum updated to 697
pagenum updated to 698
pagenum updated to 699
pagenum updated to 700
pagenum updated to 701
pagenum updated to 702
pagenum updated to 703
pagenum updated to 704
pagenum updated to 705
pagenum updated to 706
pagenum updated to 707
pagenum updated to 708
pagenum updated to 709
pagenum updated to 710
pagenum updated to 711
pagenum updated to 712
pagenum updated to 713
pagenum updated to 714
pagenum updated to 715
pagenum updated to 716
pagenum updated to 717
pagenum updated to 718
pagenum updated to 719
pagenum updated to 720
pagenum updated to 721
pagenum updated to 722
pagenum updated to 723
pagenum updated to 724
pagenum updated to 725
pagenum updated to 726
pagenum updated to 727
pagenum updated to 728
pagenum updated to 729
pagenum updated to 730
pagenum updated to 731
pagenum updated to 732
pagenum updated to 733
pagenum updated to 734
pagenum updated to 735
pagenum updated to 736
pagenum updated to 737
pagenum updated to 738
pagenum updated to 739
pagenum updated to 740
pagenum updated to 741
pagenum updated to 742
pagenum updated to 743
pagenum updated to 744
pagenum updated to 745
pagenum updated to 746
pagenum updated to 747
pagenum updated to 748
pagenum updated to 749
pagenum updated to 750
pagenum updated to 751
pagenum updated to 752
pagenum updated to 753
pagenum updated to 754
pagenum updated to 755
pagenum updated to 756
pagenum updated to 757
pagenum updated to 758
pagenum updated to 759
pagenum updated to 760
pagenum updated to 761
pagenum updated to 762
pagenum updated to 763
pagenum updated to 764
pagenum updated to 765
pagenum updated to 766
pagenum updated to 767
pagenum updated to 768
pagenum updated to 769
pagenum updated to 770
pagenum updated to 771
pagenum updated to 772
pagenum updated to 773
pagenum updated to 774
pagenum updated to 775
pagenum updated to 776
pagenum updated to 777
pagenum updated to 778
pagenum updated to 779
pagenum updated to 780
pagenum updated to 781
pagenum updated to 782
pagenum updated to 783
pagenum updated to 784
pagenum updated to 785
pagenum updated to 786
pagenum updated to 787
pagenum updated to 788
pagenum updated to 789
pagenum updated to 790
pagenum updated to 791
pagenum updated to 792
pagenum updated to 793
pagenum updated to 794
pagenum updated to 795
pagenum updated to 796
pagenum updated to 797
pagenum updated to 798
pagenum updated to 799
pagenum updated to 800
pagenum updated to 801
pagenum updated to 802
pagenum updated to 803
pagenum updated to 804
pagenum updated to 805
pagenum updated to 806
pagenum updated to 807
pagenum updated to 808
pagenum updated to 809
pagenum updated to 810
pagenum updated to 811
pagenum updated to 812
pagenum updated to 813
pagenum updated to 814
pagenum updated to 815
pagenum updated to 816
pagenum updated to 817
pagenum updated to 818
pagenum updated to 819
pagenum updated to 820
pagenum updated to 821
pagenum updated to 822
pagenum updated to 823
pagenum updated to 824
pagenum updated to 825
pagenum updated to 826
pagenum updated to 827
pagenum updated to 828
pagenum updated to 829
pagenum updated to 830
pagenum updated to 831
pagenum updated to 832
pagenum updated to 833
pagenum updated to 834
pagenum updated to 835
pagenum updated to 836
pagenum updated to 837
pagenum updated to 838
pagenum updated to 839
pagenum updated to 840
pagenum updated to 841
pagenum updated to 842
pagenum updated to 843
pagenum updated to 844
pagenum updated to 845
pagenum updated to 846
pagenum updated to 847
pagenum updated to 848
pagenum updated to 849
pagenum updated to 850
pagenum updated to 851
pagenum updated to 852
pagenum updated to 853
pagenum updated to 854
pagenum updated to 855
pagenum updated to 856
pagenum updated to 857
pagenum updated to 858
pagenum updated to 859
pagenum updated to 860
pagenum updated to 861
pagenum updated to 862
pagenum updated to 863
pagenum updated to 864
pagenum updated to 865
pagenum updated to 866
pagenum updated to 867
pagenum updated to 868
pagenum updated to 869
pagenum updated to 870
pagenum updated to 871
pagenum updated to 872
pagenum updated to 873
pagenum updated to 874
pagenum updated to 875
pagenum updated to 876
pagenum updated to 877
pagenum updated to 878
pagenum updated to 879
pagenum updated to 880
pagenum updated to 881
pagenum updated to 882
pagenum updated to 883
pagenum updated to 884
pagenum updated to 885
pagenum updated to 886
pagenum updated to 887
pagenum updated to 888
pagenum updated to 889
pagenum updated to 890
pagenum updated to 891
pagenum updated to 892
pagenum updated to 893
pagenum updated to 894
pagenum updated to 895
pagenum updated to 896
pagenum updated to 897
pagenum updated to 898
pagenum updated to 899
pagenum updated to 900
pagenum updated to 901
pagenum updated to 902
pagenum updated to 903
pagenum updated to 904
pagenum updated to 905
pagenum updated to 906
pagenum updated to 907
pagenum updated to 908
pagenum updated to 909
pagenum updated to 910
pagenum updated to 911
pagenum updated to 912
pagenum updated to 913
pagenum updated to 914
pagenum updated to 915
pagenum updated to 916
pagenum updated to 917
pagenum updated to 918
pagenum updated to 919
pagenum updated to 920
pagenum updated to 921
pagenum updated to 922
pagenum updated to 923
pagenum updated to 924
pagenum updated to 925
pagenum updated to 926
pagenum updated to 927
pagenum updated to 928
pagenum updated to 929
pagenum updated to 930
pagenum updated to 931
pagenum updated to 932
pagenum updated to 933
pagenum updated to 934

pagenum updated to 935
pagenum updated to 936
pagenum updated to 937
pagenum updated to 938
pagenum updated to 939
pagenum updated to 940
pagenum updated to 941
pagenum updated to 942
pagenum updated to 943
pagenum updated to 944
pagenum updated to 945
pagenum updated to 946
pagenum updated to 947
pagenum updated to 948
pagenum updated to 949
pagenum updated to 950
pagenum updated to 951
pagenum updated to 952
pagenum updated to 953
pagenum updated to 954
pagenum updated to 955
pagenum updated to 956
pagenum updated to 957
pagenum updated to 958
pagenum updated to 959
pagenum updated to 960
pagenum updated to 961
pagenum updated to 962
pagenum updated to 963
Processed ratings for batch #0 of games.
pagenum updated to 2
pagenum updated to 3
pagenum updated to 4
pagenum updated to 5
pagenum updated to 6
pagenum updated to 7
pagenum updated to 8
pagenum updated to 9
pagenum updated to 10
pagenum updated to 11
pagenum updated to 12
pagenum updated to 13
pagenum updated to 14
pagenum updated to 15
pagenum updated to 16
pagenum updated to 17
pagenum updated to 18
pagenum updated to 19
pagenum updated to 20
pagenum updated to 21
pagenum updated to 22
pagenum updated to 23
pagenum updated to 24
pagenum updated to 25
pagenum updated to 26
pagenum updated to 27
pagenum updated to 28
pagenum updated to 29
pagenum updated to 30
pagenum updated to 31
pagenum updated to 32
pagenum updated to 33
pagenum updated to 34
pagenum updated to 35
pagenum updated to 36
pagenum updated to 37
pagenum updated to 38
pagenum updated to 39
pagenum updated to 40
pagenum updated to 41

In [ ]:
df_ratings